# Generated by Django 3.0.5 on 2020-05-03 13:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Guest', models.CharField(blank=True, max_length=100)),
                ('Contact', models.CharField(blank=True, max_length=100)),
                ('Details', ckeditor.fields.RichTextField(blank=True)),
                ('Location', models.CharField(max_length=250)),
                ('Event_DT', models.DateTimeField(verbose_name='Date_Publish')),
                ('Food', models.CharField(choices=[('No', 'No'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=15)),
                ('T_shirt', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
