# Generated by Django 3.0.5 on 2020-05-03 17:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_upcoming_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Guest', models.CharField(blank=True, max_length=100)),
                ('Details', ckeditor.fields.RichTextField(blank=True)),
                ('Location', models.CharField(max_length=250)),
                ('Event_DT', models.DateTimeField(verbose_name='Date_Publish')),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
