# Generated by Django 3.0.5 on 2020-05-03 16:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0002_donate_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quran_hadith_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quran_hadith', ckeditor.fields.RichTextField()),
                ('Source', models.CharField(max_length=50)),
            ],
        ),
    ]
