# Generated by Django 3.0.5 on 2020-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0003_quran_hadith_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakat_Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_banking_name', models.CharField(max_length=80)),
                ('Mobile_number', models.CharField(max_length=50)),
            ],
        ),
    ]
