# Generated by Django 3.0.5 on 2020-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0004_zakat_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakat_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=40)),
                ('Branch_name', models.CharField(max_length=35)),
                ('Account_name', models.CharField(max_length=20)),
                ('Account_number', models.CharField(max_length=30)),
                ('Swift_code', models.CharField(max_length=20)),
            ],
        ),
    ]
