# Generated by Django 3.0.5 on 2020-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_completed_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Pdf_file', models.FileField(upload_to='Upcoming_projects/%Y/%m/%d/')),
            ],
        ),
    ]
