# Generated by Django 3.0.5 on 2020-05-02 16:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_DT', models.CharField(blank=True, max_length=150)),
                ('Short_describe', models.CharField(blank=True, max_length=250)),
                ('Details', ckeditor.fields.RichTextField()),
                ('Gallery_image', models.ImageField(upload_to='Gallery')),
            ],
        ),
    ]
