# Generated by Django 3.0.5 on 2020-05-02 16:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Short_describe', models.CharField(blank=True, max_length=350)),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('Date', models.DateTimeField(verbose_name='Date_Publish')),
            ],
        ),
    ]
