# Generated by Django 3.0.5 on 2020-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_video_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_gallery',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
