# Generated by Django 3.0.5 on 2020-05-03 18:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', ckeditor.fields.RichTextField()),
                ('Image', models.ImageField(upload_to='About')),
            ],
        ),
    ]
