# Generated by Django 3.0.5 on 2020-05-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0002_why_choose_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=350)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
    ]
