# Generated by Django 3.0.5 on 2020-05-04 13:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0003_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
