# Generated by Django 3.0.5 on 2020-05-03 16:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Bio_data', ckeditor.fields.RichTextField(blank=True)),
                ('Image', models.ImageField(upload_to='Team')),
                ('status', models.CharField(choices=[('I AM NEW!', 'I AM NEW!'), ('I AM OLD!', 'I AM OLD!')], max_length=12)),
            ],
        ),
    ]
