# Generated by Django 3.0.5 on 2020-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Registration', models.CharField(blank=True, max_length=100)),
                ('Working_Area', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='Doctor_team')),
            ],
        ),
    ]
