# Generated by Django 3.0.5 on 2020-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_doctor_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Image', models.ImageField(upload_to='Adviser_team')),
            ],
        ),
    ]
