# Generated by Django 3.0.7 on 2020-09-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=150)),
                ('Body', models.CharField(max_length=350)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
