# Generated by Django 3.0.7 on 2020-09-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Full_Name', models.CharField(max_length=150)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Institute', models.CharField(max_length=150)),
                ('Contact', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Joined', models.DateTimeField(auto_now_add=True)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('T_Shairt', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=6)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15)),
                ('Blood_Group', models.CharField(choices=[('Do not know yet', 'Do not know yet'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=20)),
                ('Picture', models.ImageField(upload_to='Profile_picture')),
                ('I_Agree_to_Terms', models.BooleanField(default=False)),
            ],
        ),
    ]
