# Generated by Django 3.0.5 on 2020-05-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=100)),
                ('Mail', models.CharField(max_length=100)),
                ('Meet_Time', models.CharField(max_length=50)),
            ],
        ),
    ]
