# Generated by Django 3.0.5 on 2020-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Primary_logo', models.ImageField(upload_to='Logo')),
                ('Secondary_logo', models.ImageField(upload_to='Logo')),
            ],
        ),
    ]
