# Generated by Django 3.0.5 on 2020-05-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0002_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slider_title', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=150)),
                ('Slider_img', models.ImageField(upload_to='Slider')),
            ],
        ),
    ]
