# Generated by Django 3.0.5 on 2020-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_foap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Field_1', models.CharField(blank=True, max_length=250)),
                ('Field_2', models.CharField(blank=True, max_length=250)),
                ('Field_3', models.CharField(blank=True, max_length=250)),
                ('Field_4', models.CharField(blank=True, max_length=250)),
                ('Field_5', models.CharField(blank=True, max_length=250)),
                ('Amount', models.IntegerField()),
                ('Choice', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], max_length=10)),
                ('Link', models.CharField(max_length=150)),
                ('Button_name', models.CharField(max_length=50)),
            ],
        ),
    ]
