# Generated by Django 3.0.5 on 2020-05-02 14:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0005_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Short_describe', models.CharField(max_length=150)),
                ('Details', ckeditor.fields.RichTextField()),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('Image_post', models.ImageField(upload_to='News')),
            ],
        ),
    ]
