# Generated by Django 3.0.5 on 2020-05-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Event_DT', models.DateTimeField(verbose_name='Publish Date')),
                ('Events_Image', models.ImageField(upload_to='Event')),
            ],
        ),
    ]
