# Generated by Django 3.0.5 on 2020-05-02 14:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=100)),
                ('Comment', ckeditor.fields.RichTextField()),
                ('Image_review', models.ImageField(upload_to='Review')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_DT',
            field=models.DateTimeField(verbose_name='Date_Publish'),
        ),
    ]
