# Generated by Django 3.0.7 on 2020-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0009_auto_20200502_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Href', models.CharField(max_length=500)),
                ('Class_Name', models.CharField(max_length=150)),
            ],
        ),
    ]
